apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "santricity-csi.fullname" . }}-controller
  labels:
    {{- include "santricity-csi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "santricity-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "santricity-csi.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.controllerName }}
      containers:
        - name: csi-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
            - "--controller=true"
            - "--node=false"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SANTRICITY_ENDPOINT
              value: "{{ .Values.controller.endpoint }}"
            - name: SANTRICITY_DATA_IPS
              value: "{{ .Values.controller.dataIPs }}"
            - name: SANTRICITY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "santricity-csi.secretName" . }}
                  key: username
            - name: SANTRICITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "santricity-csi.secretName" . }}
                  key: password
            - name: SANTRICITY_VERIFY_TLS
              value: "{{ .Values.controller.verifyTLS }}"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        # Sidecars
        - name: csi-provisioner
          image: "{{ .Values.sidecars.provisioner.image }}"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata=true"
            - "--leader-election=true"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: "{{ .Values.sidecars.attacher.image }}"
          args:
            - "--leader-election=true"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: "{{ .Values.sidecars.resizer.image }}"
          args:
            - "--leader-election=true"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}