{{- if not .Values.controller.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "santricity-csi.fullname" . }}-credentials
  labels:
    {{- include "santricity-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.controller.credentials.username | quote }}
  password: {{ .Values.controller.credentials.password | quote }}
{{- end }}