{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.controllerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "santricity-csi.labels" . | nindent 4 }}
    app: santricity-csi-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.nodeName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "santricity-csi.labels" . | nindent 4 }}
    app: santricity-csi-node
{{- end -}}