{{- range $i, $sc := .Values.storageClasses }}
{{- if $i }}
---
{{- end }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $sc.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ $sc.isDefault | default "false" }}"
provisioner: santricity.scaleoutsean.github.io
parameters:
  poolID: {{ $sc.poolID | quote }}
  {{- range $key, $value := $sc.parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
reclaimPolicy: {{ $sc.reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ $sc.volumeBindingMode | default "Immediate" }}
allowVolumeExpansion: {{ $sc.allowVolumeExpansion | default true }}
{{- end }}
