apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: santricity
provisioner: santricity.scaleoutsean.github.io
parameters:
  poolName: "data"
  mediaType: "ssd"
  blockSize: "4096" # Forces 4k sector size
  fsType: "xfs"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true  